### ISSUE TITLE
Add objects and extend animaton

### ISSUE THREAD

**Issue by alberttheprince** [Qbox-project/qbx_fireworks#11]
### The problem

Currently fireworks go off once or twice in the sky, usually leaving the user unable to see them. It's kind of boring and lame, and it should last maybe 10-15 seconds per firework.

Additionally, no props are in the player's hand or on the ground when the firework is launched.

### Ideal solution

add props/objects and extend the fireworks time.

### Alternative solutions

Keep it as is

### Additional context

This is a purely RP/cosmetic resource and serves little to no game mechanic function. It should be done in a way that is really interesting and fun to use.

**Comment by Manason** [comment]
This sounds like a blocking issue for release as without this feature, this resource may not be high enough quality for our standards

**Comment by mafewtm** [comment]
All requests from this issue have been added in #13
